FROM tensorflow/tensorflow:latest-gpu

RUN apt-get install -y git;
RUN git clone https://github.com/MitsuhiroIto/YAD2K.git;
RUN cd YAD2K && \
    pip install numpy && \
    pip install keras && \
    pip install tensorflow && \
    pip install h5py && \
    pip install pillow && \
    wget http://pjreddie.com/media/files/yolo.weights && \
    wget https://raw.githubusercontent.com/pjreddie/darknet/master/cfg/yolo.cfg  && \
    python yad2k.py yolo.cfg yolo.weights model_data/yolo.h5
